### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by davepwsmith** [mfenner/jekyll-pandoc#1]
Using this gem I can't get syntax highlighting to work either via jekyll or via pandoc. Is this a known problem/feature?

**Comment by hstojic** [comment]
Hi there, anyone has some advice how to solve this issue?

**Comment by serranomorante** [comment]
No syntax highlighting? 😢

**Comment by serranomorante** [comment]
> Hi there, anyone has some advice how to solve this issue?

I just use [this script](https://github.com/jgm/pandoc/issues/7860#issuecomment-1018696254) to generate a `pygments.css` file.
From there you just have to add that file to your html and it will highlight your code blocks.
