### ISSUE TITLE
jekyll v3

### ISSUE THREAD

**Issue by edsu** [mfenner/jekyll-pandoc#5]
It would be great to have jekyll v3 support, especially for incremental build support.

**Comment by edsu** [comment]
I've got a working version [over here](https://github.com/edsu/jekyll-pandoc/tree/jekyll3). I'll send a pull request if you want, or we can wait till jekyll 3 is actually out of beta.

**Comment by tlnagy** [comment]
Any update on this? https://github.com/jekyll/jekyll/releases/tag/v3.0.1 is released now.

**Comment by edsu** [comment]
I've been using [my jekyll3 branch] with Jekyll v3.0.1. But I haven't tested with jekyll-pandoc yet. As you can see my branch is greatly simplified since Jekyll 3 doesn't require monkey patching anymore.

**Comment by mfenner** [comment]
Let me look into this again. Unfortunately I made a few changes that broke the pull request by @edsu.

**Comment by tlnagy** [comment]
No rush. Jekyll v3 is just simpler (e.g. doesn't require the whole nodejs stack on debian) which is nice. Not really pressing.

**Comment by williford** [comment]
@edsu, I've been using your fork (with jekyll 3.0.1). Thanks for your (and Martin's) work!

**Comment by mfenner** [comment]
@edsu and @williford I have finally added proper jekyll 3 support in a `2.0` release today.
